server:
  port: 8888
  servlet:
    session:
      timeout: 60

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sec?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 1234
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
